# Documentation: https://rmk.rs/docs/configuration.html
[keyboard]
name = "Kabarga RMK"
product_name = "Kabarga RMK"
vendor_id = 0x2c3b
product_id = 0x5423
manufacturer = "aroum"
chip = "nrf52840"

[host]
unlock_keys = [[0, 0], [0, 5]]

[matrix]
row_pins = ["P0_08", "P0_20", "P0_17", "P0_31", "P0_29", "P0_02", "P1_15"]
col_pins = ["P1_06", "P1_04", "P0_11", "P1_00", "P0_24", "P0_22"]

[layout]
rows = 7
cols = 6
layers = 4
keymap = [
    # Layer 0: Base
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["CapsLock", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["LCtrl", "LGui", "LAlt", "Space", "MO(1)", "Left"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus"],
        ["Y", "U", "I", "O", "P", "LeftBracket"]
    ],
    # Layer 1: Fn / Bluetooth
    [
        ["Escape", "User0", "User1", "User2", "_", "User5"],
        ["User6", "_", "_", "_", "_", "_"],
        ["CapsLock", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["LCtrl", "LGui", "LAlt", "Space", "MO(1)", "Left"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus"],
        ["Y", "U", "I", "O", "P", "LeftBracket"]
    ],
    # Layer 2
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["CapsLock", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["LCtrl", "LGui", "LAlt", "Space", "MO(1)", "Left"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus"],
        ["Y", "U", "I", "O", "P", "LeftBracket"]
    ],
    # Layer 3
    [
        ["Equal", "Backspace", "RightBracket", "Backslash", "Semicolon", "Quote"],
        ["H", "J", "K", "L", "Enter", "Comma"],
        ["N", "M", "Dot", "Slash", "UP", "Down"],
        ["Right", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus"],
        ["Equal", "Backspace", "RightBracket", "Backslash", "Semicolon", "Quote"],
        ["Enter", "Comma", "Dot", "Slash", "UP", "Down"]
    ]
]

[light]
numslock = { pin = "P1_11", low_active = false }
capslock = { pin = "P0_10", low_active = false }
scrolllock = { pin = "P0_09", low_active = false }

[storage]
enabled = true

[ble]
enabled = true
battery_adc_pin = "vddh"
charge_led = { pin = "P1_13", low_active = false }
